# Generated by Django 4.1.5 on 2023-01-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_book_cover_genre_genre_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_picture',
            field=models.ImageField(blank=True, upload_to='genres/'),
        ),
    ]
